server:
  port: 30301
spring:
  data:
    mongodb:
      uri: mongodb://192.168.11.118:31017/
      database: jjsk_mp_fileserver
  servlet:
    # limit upload file size
    multipart:
      max-file-size: 16GB
      max-request-size: 1024GB
base:
  fs:
    base-preview-url: http://192.168.11.118:30071/file/no_token
    download-file-path: /opt